services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./docker/requirements.txt:/app/requirements.txt
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./webpack.config.js:/app/webpack.config.js
      - ./captures:/app/captures
      - node_modules:/app/node_modules
    devices:
      - "/dev:/dev"
    group_add:
      - video
    privileged: true
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - CAMERA_ID=0
      - HOME=/app
      - CAMERA_DEVICES=/dev/video*
    command: >
      bash -c "npm run dev & 
              uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload --reload-dir /app/src"
    restart: unless-stopped

volumes:
  node_modules: